### ISSUE TITLE
Git: multi-pack-index builtin always shows progress

### ISSUE THREAD

**Issue by wilbaker** [microsoft/git#179]
Splitting this out as a separate issue from #177 

The `multi-pack-index` builtin shows progress during its output. There is no way to turn it off right now. This means that when we have an error, stderr is filled with progress indicators and the actual error message may be truncated in our logging.

Update git to allow --no-progress and use this argument in the background operations.

**Comment by derrickstolee** [comment]
Here are some hints:

You can take most of the changes from #172, but with the following replacements:

1. `builtin/multi-pack-index.c` instead of `builtin/commit-graph.c`.
2. `Documentation/git-multi-pack-index.txt` instead of `Documentation/git-commit-graph.c`
3. `t/t5319-multi-pack-index.sh` instead of `t/t5318-commit-graph.sh`

**Comment by wilbaker** [comment]
Fixed by #186
