### ISSUE TITLE
Sparse-checkout: recover gracefully from canceled 'set' command

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#287]
A user reported a situation like the following:

```sh
$ git sparse-checkout set <dir1> <dir2> ... <dirN>
Receiving packfile 1/33 with 4000 objects (bytes received): 1068014587, done
^C

$ git sparse-checkout set
Receiving packfile 1/32 with 4000 objects (bytes received): 876319629, done.
```

So, somehow the first command stored some state of the sparse-checkout file but did not fully succeed in downloading the blob data, and that is affecting the second command.

What confuses me is that we already have logic in the sparse-checkout builtin that should not be committing a pattern set to disk until after the working directory is updated to match. Perhaps there is something wrong with that logic.

**Comment by AtOMiCNebula** [comment]
Regretfully, this was user error.  Higher-level tooling was keeping large directories in the list of paths that was being sent to `git sparse-checkout`, and I didn't realize it.  Once this was clear, the higher-order tooling was tamed, and `git sparse-checkout` did indeed return to the expected behavior (of forgetting about the no-longer-needed content). 😇

**Comment by derrickstolee** [comment]
@AtOMiCNebula: Thank you for confirming! I'll close this issue, but we'll always have it to re-open if we need it.
