### ISSUE TITLE
Pre/post-command hooks and post-index-change hook might inherit stdin

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/git#492]
If a user pastes multiple commands into a terminal, they expect those commands to be run in order.

However, the later lines become part of consumed stdin, depending on the existence of a post-command hook or a post-index-change hook. This might be due to those hook implementations taking stdin in a way they shouldn't, but maybe Git shouldn't be passing stdin to these hooks in the first place.

**Comment by rimrul** [comment]
To me this issue doesn't sound like the root cause is an issue in how git handles hooks. If these multiple lines are a single paste, none of it should end up in the first commands `stdin`.

Let's say the first command is `vim`, I wouldn't expect the following lines of the paste to end up as input to the text editor either.

So if they end up in `git`s `stdin`, that already doesn't sound correct.

**Comment by dscho** [comment]
> This might be due to those hook implementations taking stdin in a way they shouldn't

Judging by the unfortunate regression in v2.36.0 whereby hooks are _no longer_ attached to stdio, this seems to be intended behavior.

**Comment by derrickstolee** [comment]
I agree, I think this is an expected behavior and the hooks should be modified, not Git.
